// <auto-generated />
namespace QZCHY.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class station1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(station1));
        
        string IMigrationMetadata.Id
        {
            get { return "201705170812203_station1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
